### ISSUE TITLE
Fix nikudot and dagesh in hebrew month names

### ISSUE THREAD

**Issue by mjradwin** [hebcal/dotcom#10]
Dear Michael,

thanks for hebcal, It's very useful!
I've noticed that the spelling of the nikudot and the dagesh in names of some months on www.hebcal.com and in the respective daily rss is incorrect (as far as I know, this has nothing to do with the *nix command, which outputs ktiv male):

בְּתִּשְׁרֵי should be בְּתִשְׁרֵי
בְּכִּסְלֵו should be בְּכִסְלֵו
בְּשְׁבָט should be בִּשְׁבָט
בְּאַדָר should be בַּאֲדָר
בְּאִיָיר should be בְּאִיָּר
בְּתָּמוּז should be בְּתַמּוּז
בְּאֱלוּל should be בֶּאֱלוּל

Best wishes,
Andrey Rozenberg

**Comment by dsadinoff** [comment]
This is not great.  Iyyar is spelled כתב מלא in modern Hebrew.  I strongly recommend reverting this for Iyyar.

**Comment by mjradwin** [comment]
So instead of 
בְּאִיָּר
it should actually be
בְּאִיָיר
as it was originally?

**Comment by mjradwin** [comment]
To be clear, this is showing up on a [Hebrew Date Converter page like this one](https://www.hebcal.com/converter/?gd=2&gm=5&gy=2020&g2h=1)

ח׳ בְּאִיָּר תש״פ

would be better instead as this?

ח׳ בְּאִיָיר תש״פ

**Comment by dsadinoff** [comment]
I think so.  If Andrey insists that it's wrong then I would suggest removing the nikud entirely (maybe only for Iyyar) rather than show כתב חסר.  It looks weird and wrong.

**Comment by mjradwin** [comment]
Deployed a couple of weeks ago.
