### ISSUE TITLE
Candle Lighting offset in Shabbat API

### ISSUE THREAD

**Issue by lukecarbis** [hebcal/dotcom#13]
Currently there is a `m` parameter, to specify a minutes after sundown for Havdalah times.

However, there is no parameter for specifying minutes before sunset for Candle Lighting times.

While most of the world uses 18 minutes, here in Jerusalem we light the candles at 40 minutes before sunset.

My proposal is to retain the `m` parameter, for backward compatibility, but introduce two new parameters:

- `cl_offset=18` - Candle Lighting offset minutes before sunset, defaults to 18
- `h_offset=50` - Havdalah offset minutes after sunset (exactly the same as the `m` parameter)

Here are some references on the topic:
[Judaism Stack Exchange question](http://judaism.stackexchange.com/questions/13472/40-minutes-offset-for-candle-lighting)
[Chabad.org candle lighting times use 40 minutes for Jerusalem](http://www.chabad.org/calendar/candleLighting_cdo/c/247/jewish/Candle-Lighting.htm#locationId=247&locationType=1&tdate=6/14/2015)

**Comment by lukecarbis** [comment]
I just discovered that there is, in fact, a parameter (`b`) for the candle lighting offset, it's just not documented on the [Shabbat Times Rest API](https://www.hebcal.com/home/197/shabbat-times-rest-api) page.

But I have tested and it works.

Feel free to close this ticket, or if you wanted to update the docs first, and then close it, that works too.

**Comment by mjradwin** [comment]
Updated the documentation to explicitly mention the `b` parameter. Thanks!
