### ISSUE TITLE
Parashat leyning information in Shabbat times REST API

### ISSUE THREAD

**Issue by lukecarbis** [hebcal/dotcom#15]
When specifying the `ss=on` parameter in the Jewish Calendar REST API, one of the data points returned is the Parashat:

```
"category": "parashat",
"date": "2015-06-27",
"hebrew": "פרשת חקת",
"leyning": {
    "1": "Numbers 19:1 - 19:17",
    "2": "Numbers 19:18 - 20:6",
    "3": "Numbers 20:7 - 20:13",
    "4": "Numbers 20:14 - 20:21",
    "5": "Numbers 20:22 - 21:9",
    "6": "Numbers 21:10 - 21:20",
    "7": "Numbers 21:21 - 22:1",
    "haftarah": "Judges 11:1 - 11:33",
    "torah": "Numbers 19:1 - 22:1"
},
"link": "http://www.hebcal.com/sedrot/chukat",
"title": "Parashat Chukat"
```

However, in the Shabbat Times REST API, which also includes the Parashat, we only get this returned:

```
"category": "parashat",
"date": "2015-06-27",
"hebrew": "פרשת חקת",
"link": "http://www.hebcal.com/sedrot/chukat",
"title": "Parashat Chukat"
```

This is missing the `leyning` information.

Would it be possible to have this included in the Shabbat Times REST API?

By the way, thank you so much for all the work you've put into this!

**Comment by mjradwin** [comment]
Deployed to hebcal.com today.
