### ISSUE TITLE
Missing Parashat in Shabbat REST API

### ISSUE THREAD

**Issue by lukecarbis** [hebcal/dotcom#16]
It seems that during Sukkot, the Parashat readings are missing.

e.g. http://www.hebcal.com/shabbat/?cfg=json&m=50&b=18&geo=city&city=IL-Jerusalem

**Comment by mjradwin** [comment]
Our API doesn't yet expose leyning for holidays. This would be an excellent enhancement.

**Comment by lukecarbis** [comment]
Can confirm that this is also the case during Hanukkah.

**Comment by mjradwin** [comment]
Confirmed. It's the same general-purpose missing feature.

We will endeavor to work this feature into our Shabbat REST API, but in the interim, you can get a nearly-complete set of holiday leyning data in CSV form from here:

https://www.hebcal.com/sedrot/#download

**Comment by mjradwin** [comment]
This is fixed now. For example, here is the Torah reading in the API for Sukkot

https://www.hebcal.com/shabbat?cfg=json&city=IL-Jerusalem&gy=2020&gm=10&gd=3

```json
{
  "items": [
    {
      "title": "Sukkot I",
      "date": "2020-10-03",
      "category": "holiday",
      "subcat": "major",
      "yomtov": true,
      "hebrew": "סוכות יום א׳",
      "leyning": {
        "1": "Leviticus 22:26 - 22:33",
        "2": "Leviticus 23:1 - 23:3",
        "3": "Leviticus 23:4 - 23:8",
        "4": "Leviticus 23:9 - 23:14",
        "5": "Leviticus 23:15 - 23:22",
        "6": "Leviticus 23:23 - 23:32",
        "7": "Leviticus 23:33 - 23:44",
        "torah": "Leviticus 22:26-23:44",
        "haftarah": "Zechariah 14:1-21",
        "maftir": "Numbers 29:12 - 29:16"
      },
      "link": "https://www.hebcal.com/holidays/sukkot-2020?i=on&utm_source=js&utm_medium=api",
      "memo": "Feast of Booths"
    }
  ]
}
```

Shana Tova!
