### ISSUE TITLE
Shabbat REST API, showing Sabbath times for the next week

### ISSUE THREAD

**Issue by lukecarbis** [hebcal/dotcom#17]
Testing this in Australia, GMT +10.

If I check the Shabbat REST API on a Sunday morning, I receive no candle lighting times, only havdalah times.

In my opinion, this would be the expected behaviour _after_ candle lighting and _before_ havdalah, but this result occurs _after_ havdalah.

My request includes a timezone indicator (`tzid=Australia/Brisbane`). I wonder if maybe the timezone isn't respected when calculating which week's information to return?

**Comment by mjradwin** [comment]
This is definitely a bug. We're currently always using the local time (`America/New_York`) to determine which week we should display.

**Comment by mjradwin** [comment]
We made a change eca12b9612152c7fac6a28d871259545ffd8fa2a and deployed to hebcal.com.

Let us know if it works for you?

**Comment by lukecarbis** [comment]
I'll set a reminder to check this Saturday night.

**Comment by lukecarbis** [comment]
Just checked at 7pm (10 minutes after Havdalah) and I don't think it's working. 

Url: http://www.hebcal.com/shabbat/?cfg=json&m=50&b=18&geo=pos&latitude=-26.684759&longitude=153.053738&tzid=Australia/Brisbane

Results:
```
{"title":"-26.684759, 153.053738, Australia/Brisbane","items":[{"link":"http://www.hebcal.com/sedrot/lechlecha","hebrew":"פרשת לך־לך","category":"parashat","leyning":{"5":"Genesis 14:21 - 15:6","6":"Genesis 15:7 - 17:6","torah":"Genesis 12:1 - 17:27","3":"Genesis 13:5 - 13:18","2":"Genesis 12:14 - 13:4","4":"Genesis 14:1 - 14:20","maftir":"Genesis 17:24 - 17:27","1":"Genesis 12:1 - 12:13","7":"Genesis 17:7 - 17:27","triennial":{"7":"Genesis 17:24 - 17:27","1":"Genesis 16:1 - 16:6","maftir":"Genesis 17:24 - 17:27","5":"Genesis 17:7 - 17:17","6":"Genesis 17:18 - 17:23","3":"Genesis 16:10 - 16:16","2":"Genesis 16:7 - 16:9","4":"Genesis 17:1 - 17:6"},"haftarah":"Isaiah 40:27 - 41:16"},"date":"2015-10-24","title":"Parashat Lech-Lecha"},{"category":"havdalah","hebrew":"הבדלה - 50 דקות","date":"2015-10-24T18:49:00+10:00","title":"Havdalah (50 min): 6:49pm"}],"date":"2015-10-24T09:00:35-00:00","location":{"longitude":"153.053738","geo":"pos","latitude":"-26.684759","tzid":"Australia/Brisbane","title":"-26.684759, 153.053738, Australia/Brisbane"},"link":"http://www.hebcal.com/shabbat/?m=50;b=18;geo=pos;latitude=-26.684759;longitude=153.053738;tzid=Australia%2FBrisbane;maj=on;min=on;mod=on;mf=on;ss=on;nx=on;c=on"}
```

**Comment by lukecarbis** [comment]
Sunday morning 10am checked again and it's showing candle lighting times. Pretty sure it wasn't doing that before. 

Seems to me like the week resets at 0:00 on Sunday. If that's the intended behaviour, then that makes sense to me. Feel free to close.

**Comment by mjradwin** [comment]
Yes, it used to reset Sunday 00:00 in New York. Now it resets Sunday 00:00 in the local time zone. Not as perfect as resetting the week immediately after Havdalah, but an improvement nonetheless.
