### ISSUE TITLE
Candle lightling for RH2 is missing

### ISSUE THREAD

**Issue by catalandres** [hebcal/dotcom#18]
I noticed that Hebcal recently added _hadliqat nerot_ times for the second days of _ḥag_ (...thanks!!).
If I'm not wrong, the one for the second day of RH does not seem to be appearing (https://www.hebcal.com/hebcal/?v=1&maj=on&min=on&nx=on&mf=on&ss=on&mod=on&o=on&s=on&i=off&year=2016&month=x&yt=G&lg=s&c=on&geo=zip&zip=19146&city=&geonameid=&b=18&m=42&.s=Create+Calendar).

**Comment by mjradwin** [comment]
Confirmed. It looks like the feature that @aperomsik implemented with https://github.com/aperomsik/hebcal/commit/cb1c95ee0d3ac46052b0271514b0ddbaccfd90c8 added second night of yomtov but not for 2nd evening of RH.

**Comment by mjradwin** [comment]
I believe this one was fixed long ago.
