### ISSUE TITLE
Accessing zmanim from the API

### ISSUE THREAD

**Issue by sgladstone** [hebcal/dotcom#24]
I am currently using the Jewish calendar REST API, but do not see any parameters for  getting zmanim, ie what is described at https://github.com/hebcal/hebcal/issues/68

**Comment by mjradwin** [comment]
zmanim are still experimental in hebcal, and as such are not exposed in the REST API yet. when zmanim move out of experimental status (e.g. when hebcal/hebcal#68 is closed) you can expect to see this feature implemented in the API.

**Comment by sgladstone** [comment]
What is needed to promote zmanim out of experimental status? Could I help?  I was thinking I could add zmanim to my Drupal module (https://www.drupal.org/sandbox/fountaintribe/2830659)  so that non-programmers could give feedback.

**Comment by mjradwin** [comment]
This has been implemented, finally. Documentation still forthcoming. Details here:

https://github.com/hebcal/hebcal/issues/208
