### ISSUE TITLE
Sh'vat vs Shvat

### ISSUE THREAD

**Issue by alonkama** [hebcal/dotcom#27]
When calling this URL: http://www.hebcal.com/converter/?cfg=json&g2h=1&gy=1993&gm=1&gd=23&gs=0
the return month is "hm":"Sh'vat".

But when using Sh'vat in a call, for example http://www.hebcal.com/converter/?cfg=json&h2g=1&hy=5777&hm=Sh'vat&hd=1
it results in {"error":"Unrecognized hebrew month"}
It expects the month to be called Shvat (no apostorphe)

**Comment by mjradwin** [comment]
Fixed!
