### ISSUE TITLE
Switch for excluding the 'leyning' from the JSON response in shabbat.cgi

### ISSUE THREAD

**Issue by disforw** [hebcal/dotcom#28]
In the file shabbat.cgi, I am looking to omit the 'leyning' (with an optional switch). This part of the response seems to be throwing my parser for a loop. Is it possible?

**Comment by mjradwin** [comment]
A good idea. You could send a pull request that implements the change?

**Comment by mjradwin** [comment]
This is now implemented. Compare

https://www.hebcal.com/shabbat/?cfg=json&zip=02906&m=42&gy=2019&gm=4&gd=6&leyning=1

With

https://www.hebcal.com/shabbat/?cfg=json&zip=02906&m=42&gy=2019&gm=4&gd=6&leyning=0
