### ISSUE TITLE
Havdala time on refrigerator chart?

### ISSUE THREAD

**Issue by 99littlebugs** [hebcal/dotcom#31]
Is there a way to get a yearly print out of candle lighting time and havdala time?

**Comment by mjradwin** [comment]
No. The Shabbat times refrigerator chart only displays candle lighting
times.

--

**Comment by sharonrk** [comment]
Would you be open to it being changed? Or including an option for it? 
If so, I would take a stab at implementing

**Comment by mjradwin** [comment]
Hi, thanks for using Hebcal and thanks for this suggestion. We're working on this feature and getting ready to release it.

You can append `&havdalah=1` to our Fridge shabbat times page. So if the URL from the website is this:

https://www.hebcal.com/shabbat/fridge.cgi?zip=02906&b=18&M=off&m=42&lg=s&year=5782

Then you can get Havdalah times like this:

https://www.hebcal.com/shabbat/fridge.cgi?zip=02906&b=18&M=off&m=42&lg=s&year=5782&havdalah=1

Please take a look and tell us what you think!

**Comment by 99littlebugs** [comment]
This looks great, thanks!

**Comment by mjradwin** [comment]
Thanks for the feedback. We have deployed the change. There is now a checkbox at the bottom of the page that says "Show Havdalah times" and it will dynamically toggle the times on/off

Unchecked:

<img width="484" alt="Screen Shot 2021-08-04 at 12 32 39 PM" src="https://user-images.githubusercontent.com/3769045/128243607-545a8e80-83b2-4385-bf48-76bfba1eaed5.png">

Checked:

<img width="573" alt="Screen Shot 2021-08-04 at 12 32 46 PM" src="https://user-images.githubusercontent.com/3769045/128243704-1e346b65-eb2d-423b-abe2-64e428766294.png">
