### ISSUE TITLE
Update docs to reflect HTTP to HTTPS redirects. 

### ISSUE THREAD

**Issue by sgladstone** [hebcal/dotcom#32]
The documentation at: https://www.hebcal.com/home/195/jewish-calendar-rest-api

should be updated to reflect the requirement of using "https://" when using the API. When I use "http" such as "http://www.hebcal.com/hebcal/?v=1&cfg=json&maj=on&min=on&mod=on&nx=on&year=now&month=x&ss=on&mf=on&c=on&geo=geoname&geonameid=3448439&m=50&s=on"  the response is HTTP status 301 ( "Moved" ).  

The only way to use the API now is to use the URL such as "https://www.hebcal.com/hebcal/?v=1&cfg=json&maj=on&min=on&mod=on&nx=on&year=now&month=x&ss=on&mf=on&c=on&geo=geoname&geonameid=3448439&m=50&s=on"

Just curious: when did the redirect behavior start happening?

**Comment by mjradwin** [comment]
Thanks for pointing this out. The change to require https always is from
about 25 days ago. It corresponds to when Google Chrome decided to start
marking regular http websites as insecure.

https://github.com/hebcal/dotcom/commit/649a10f87bef7c98ea1fed046f3e74449ce788c2


--

**Comment by mjradwin** [comment]
We have updated the documentation to use only https, and have also restored the ability to query the JSON APIs with regular old http.
