### ISSUE TITLE
havdala time with hebrew translation still leave english word for minutes

### ISSUE THREAD

**Issue by roidayan** [hebcal/dotcom#40]
Test url

https://www.hebcal.com/shabbat?cfg=json&amp;geonameid=293397&lg=h&geo=geoname&m=50

return of habdala is like this where min is not translated. it was translated before, not sure when it broke.

{
title: "הַבדָלָה (50 min): 19:30",
date: "2020-09-20T19:30:00+03:00",
category: "havdalah",
title_orig: "Havdalah",
hebrew: "הבדלה"
},

should be 

{
title: "הַבדָלָה (50 דקות): 19:30",
date: "2020-09-20T19:30:00+03:00",
category: "havdalah",
title_orig: "Havdalah",
hebrew: "הבדלה"
},

**Comment by mjradwin** [comment]
Fixed
