### ISSUE TITLE
Links to tikkun.io for leyning

### ISSUE THREAD

**Issue by akivajgordon** [hebcal/dotcom#42]
First, what fantastic work you have done for the Jewish community – יישר כוחך! Thank you for all your efforts.

I'm the maintainer of an online tikkun korim web app (http://tikkun.io, [GitHub](https://github.com/akivajgordon/tikkun.io)), and I just [released a feature](https://github.com/akivajgordon/tikkun.io/releases/tag/v1.8.0) to be able to link directly to specific places in the tikkun.

I'd love to be able to jump directly from the Torah section of hebcal.com to the appropriate place in tikkun.io when I want to start practicing the leyning. It seems like a great integration opportunity between our projects.

With a little guidance, I'd be happy to implement the feature or at least do what I can to help. Interested to hear your thoughts on this.

**Comment by mjradwin** [comment]
Thanks for the suggestion!

I see you already support per-parsha links like this: https://tikkun.io/#/p/noach

One way would be to use the same format as Sefaria, which is by book, chapters and verses. This is how Sefaria does the equivalent hyperlink for the entire Parashat Noach reading:

https://www.sefaria.org/Genesis.6.9-11.32?lang=bi&aliyot=1

And if you wanted to link to the 3rd aliyah, for example, it would be

https://www.sefaria.org/Genesis.7.17-8.14?lang=bi&aliyot=1

We could consider other link formats, for example https://tikkun.io/#/p/noach/3 for the 3rd aliyah (and /m for Maftir aliyah)

**Comment by mjradwin** [comment]
Oh, I see you already support this format

https://tikkun.io/#/r/3-21-4

I suppose we could make that work pretty easily on our end

**Comment by akivajgordon** [comment]
@mjradwin – I'm open to different ideas of the formatting.

The kind like `/#/r/x-y-z` is flexible, but I do like the readability of `/#/p/noach/3` quite a bit more, and given that link in the address bar, it's very easy to see how to quickly get to, say, the 5th aliyah, for example, or even to a different parsha.

On the other hand, I've received a request for supporting triennial aliyah markers, so the `/#/p/noach/3` seems like it could be confusing or ambiguous if I ever go down that route. That makes me think the `/#/r/x-y-z` approach might be the better one at the moment, at least until I figure out if I'd be willing to commit to `/#/p/noach/3`. It's also something we can change at some point later down the line if we felt the need.

When you get the time, I'm curious about your thoughts of how you envision the UI treatment for this feature.

**Comment by mjradwin** [comment]
I was thinking about book icons with links to tikkun.io like this:

<img width="543" alt="Screen_Shot_2021-07-18_at_10_12_19_AM-2" src="https://user-images.githubusercontent.com/3769045/126076217-7319547b-e755-4a67-bf47-e09ecc8dc990.png">

**Comment by akivajgordon** [comment]
I see two UX issues with that (neither one of these is because it specifically relates to my app, just in general):

1. the icons look like small touch targets and therefore hard to activate accurately
2. it's not clear that it's taking you to a place that would be different from the linked text near it (which I think takes you over to Sefaria at the moment, if I'm not mistaken). It appears like an extension of the text, even though it wouldn't actually be. On desktop, most browsers will show you where the link is going on hover, but (a) not everyone configures their browser to show this, and (b) it's not available on mobile at all, since there is no hover concept.

I was wondering if you considered other alternatives.

**Comment by mjradwin** [comment]
Thanks for the feedback! Do you have a suggestion for an alternative UX design?

**Comment by akivajgordon** [comment]
Wow I looked at the site and saw you already deployed the change – that was incredibly fast. And based on your GitHub profile, you appear to be an absolute machine.

In any case, I actually can't think of something better at the moment that wouldn't be too intrusive on your site, so let's just leave it as you've designed it and see if there's any feedback that would require a change.

I sincerely appreciate your willingness to integrate with tikkun.io, and I'm super impressed at how quickly you got that out there. Thanks!

**Comment by dsadinoff** [comment]
Strong work guys. I love this app.

**Comment by akivajgordon** [comment]
@dsadinoff – I see you've added a bunch of issues for tikkun.io, so I'll just express my gratitude here in this one comment; thank you very much, and please keep 'em coming!
